#!/usr/bin/env bash
set -euo pipefail

# No model training or inference is required.
# Uses rankings_topk.csv and per_mashup_metrics.csv already generated by the
# significance workflow.

CONFIG="${CONFIG:-configs/finetune_mtfm_cold_strict_zscore_seed0.yaml}"
INPUT_ROOT="${INPUT_ROOT:-outputs/statistical_analysis/runs}"
CASE_ROOT="${CASE_ROOT:-outputs/case_studies}"
GROUND_TRUTH="${GROUND_TRUTH:-${CASE_ROOT}/ground_truth.csv}"
OUTPUT_DIR="${OUTPUT_DIR:-${CASE_ROOT}/summary}"

python -u scripts/export_case_ground_truth.py \
  --config "${CONFIG}" \
  --output "${GROUND_TRUTH}" \
  --split test \
  --head_ratio 0.20 \
  --middle_ratio 0.30

python -u scripts/analyze_case_studies.py \
  --root "${INPUT_ROOT}" \
  --ground_truth "${GROUND_TRUTH}" \
  --output_dir "${OUTPUT_DIR}" \
  --config "${CONFIG}" \
  --k 10

echo
echo "Finished."
echo "Report:          ${OUTPUT_DIR}/case_study_report.md"
echo "Selected cases:  ${OUTPUT_DIR}/cases_selected.csv"
echo "Rankings:        ${OUTPUT_DIR}/case_rankings.csv"
echo "Ground truth:    ${OUTPUT_DIR}/case_ground_truth.csv"
