#!/usr/bin/env bash
set -euo pipefail

# This script does not rerun the recommendation model.
# It analyzes rankings_topk.csv generated by the significance workflow.
#
# Run from the project root:
#   bash scripts/run_strict_diversity_analysis.sh

INPUT_ROOT="${INPUT_ROOT:-outputs/statistical_analysis/runs}"
OUTPUT_DIR="${OUTPUT_DIR:-outputs/diversity_analysis/summary}"

required=(
  "${INPUT_ROOT}/graph_only/seed0/rankings_topk.csv"
  "${INPUT_ROOT}/graph_only/seed1/rankings_topk.csv"
  "${INPUT_ROOT}/graph_only/seed2/rankings_topk.csv"
  "${INPUT_ROOT}/bge_only/seed0/rankings_topk.csv"
  "${INPUT_ROOT}/bge_only/seed1/rankings_topk.csv"
  "${INPUT_ROOT}/bge_only/seed2/rankings_topk.csv"
  "${INPUT_ROOT}/graph_bge_zscore/seed0/rankings_topk.csv"
  "${INPUT_ROOT}/graph_bge_zscore/seed1/rankings_topk.csv"
  "${INPUT_ROOT}/graph_bge_zscore/seed2/rankings_topk.csv"
)

for file in "${required[@]}"
do
  if [[ ! -f "${file}" ]]; then
    echo "[ERROR] Missing required file: ${file}"
    echo "Run scripts/run_strict_significance.sh first."
    exit 1
  fi
done

python -u scripts/analyze_diversity_bias.py \
  --root "${INPUT_ROOT}" \
  --output_dir "${OUTPUT_DIR}" \
  --ks 5 10

echo
echo "Finished."
echo "Report: ${OUTPUT_DIR}/diversity_report.md"
echo "Table:  ${OUTPUT_DIR}/diversity_metrics_mean_std.csv"
